[package]
name = "arbr"
version = "0.1.0"
edition = "2021"
authors = ["Thomas Eckert"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
clap = "3.0.0-beta.5"
comrak = "0.12.1"
